// Athyx developer API client — real REST endpoints per athyx.com/developers:
// base https://api.athyx.com/v1, Bearer API key (format "ath_live_...",
// generated by the athlete in their Athyx account and pasted into our
// device-connect page). Read-only, account-scoped to whoever's key it is.
// This is the one integration in the app with zero OAuth dance: the athlete
// creates a key on athyx.com, pastes it in, done — matches how the Athyx
// docs describe it being meant to be used ("for your own dashboards,
// scripts, and AI agents").

const API_BASE = "https://api.athyx.com/v1";

export type AthyxLactateZones = {
  zone1Min?: number; zone2Min?: number; zone3Min?: number;
  zone4Min?: number; zone5Min?: number; zone6Min?: number;
};

export type AthyxSession = {
  id: string;
  startedAt: string;
  sport?: string;
  durationSec?: number;
  metabolicLoad?: number;
  lactateZones?: AthyxLactateZones;
  avgLactateMmol?: number;
  peakLactateMmol?: number;
  [key: string]: unknown;
};

async function athyxFetch(path: string, apiKey: string) {
  const res = await fetch(`${API_BASE}${path}`, {
    headers: { Authorization: `Bearer ${apiKey}`, Accept: "application/json" },
  });
  if (res.status === 401) throw new Error("Athyx API-ключ недействителен или отозван.");
  if (!res.ok) throw new Error(`Athyx API error: ${res.status} ${await res.text().catch(() => "")}`);
  return res.json();
}

// Cheap credential check used right when the athlete pastes their key in,
// before we save it — GET /v1/summary is the lightest authenticated call.
export async function verifyAthyxKey(apiKey: string): Promise<boolean> {
  try {
    await athyxFetch("/summary", apiKey);
    return true;
  } catch {
    return false;
  }
}

// GET /v1/sessions — most recent first, per the published docs.
export async function listAthyxSessions(apiKey: string, sinceIso?: string): Promise<AthyxSession[]> {
  const qs = sinceIso ? `?since=${encodeURIComponent(sinceIso)}` : "";
  const json = await athyxFetch(`/sessions${qs}`, apiKey);
  const sessions = Array.isArray(json) ? json : (json.sessions ?? json.data ?? []);
  return sessions as AthyxSession[];
}

export async function getAthyxSession(apiKey: string, sessionId: string): Promise<AthyxSession> {
  return athyxFetch(`/sessions/${sessionId}`, apiKey);
}

export async function getAthyxInsights(apiKey: string) {
  return athyxFetch("/insights", apiKey);
}

export async function getAthyxSummary(apiKey: string) {
  return athyxFetch("/summary", apiKey);
}
